#!/bin/bash
#
# Script to install DELTA dependencies on Ubuntu 14.04
#

# install virtualbox
cd ;
sudo apt-get update
sudo apt-get install virtualbox -y


# install vagrant
cd ;
sudo apt-get install vagrant